add_executable(export_gyro_propagation export_gyro_propagation.cpp)
target_link_libraries(export_gyro_propagation PRIVATE slam_core)

add_executable(export_imu_state_propagation export_imu_state_propagation.cpp)
target_link_libraries(export_imu_state_propagation PRIVATE slam_core)

add_executable(evaluate_gyro_bias_from_gt evaluate_gyro_bias_from_gt.cpp)
target_link_libraries(evaluate_gyro_bias_from_gt PRIVATE slam_core)

add_executable(evaluate_accel_bias_from_gt evaluate_accel_bias_from_gt.cpp)
target_link_libraries(evaluate_accel_bias_from_gt PRIVATE slam_core)

add_executable(demo_lm_point_alignment demo_lm_point_alignment.cpp)
target_link_libraries(demo_lm_point_alignment PRIVATE slam_core)

add_executable(optimize_imu_chain optimize_imu_chain.cpp)
target_link_libraries(optimize_imu_chain PRIVATE slam_core)
